import Foundation

/// A playable civilization. All content is original; civilizations and leaders are
/// real public-domain history. Not affiliated with any commercial strategy game.
struct Civilization: Identifiable, Hashable {
    let id: String              // lowercase slug, unique, e.g. "rome"
    let name: String            // e.g. "Rome"
    let adjective: String       // e.g. "Roman"
    let leader: String          // a real historical leader, e.g. "Augustus"
    let colorHex: String        // 6-hex RGB, no '#', visually distinct from neighbors in the list
    let abilityName: String     // short original ability title
    let abilityDescription: String   // 1 sentence, original game-design bonus
    let uniqueUnitName: String  // original-but-historical unit name, e.g. "Legion"
    let uniqueUnitReplaces: String   // base unit it replaces: one of "Warrior","Spearman","Archer","Horseman","Galley","Trireme","Swordsman","Catapult","Knight"
    let uniqueUnitNote: String  // 1 short clause describing what's special, original wording
    let cityNames: [String]     // 8-12 real historical city names for this civ
    let blurb: String           // 1-2 sentence original, evocative historical description
}

extension Civilization {
    /// The full playable roster.
    static let all: [Civilization] = [
        Civilization(
            id: "rome",
            name: "Rome",
            adjective: "Roman",
            leader: "Augustus",
            colorHex: "9E1B32",
            abilityName: "Roads of Empire",
            abilityDescription: "New cities founded near an existing city automatically begin with a connecting road, and roads cost no maintenance.",
            uniqueUnitName: "Legion",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Can build a fort once per turn while stationed in friendly territory.",
            cityNames: ["Roma", "Ostia", "Capua", "Mediolanum", "Ravenna", "Brundisium", "Tarentum", "Pompeii", "Verona", "Neapolis", "Aquileia"],
            blurb: "From seven hills beside the Tiber, Rome bound a sprawling Mediterranean world together with law, legions, and roads that still scar the earth."
        ),
        Civilization(
            id: "greece",
            name: "Greece",
            adjective: "Greek",
            leader: "Pericles",
            colorHex: "2E6FB7",
            abilityName: "Council of Citizens",
            abilityDescription: "Each city gains +1 culture for every two of its specialist citizens working in buildings.",
            uniqueUnitName: "Hoplite",
            uniqueUnitReplaces: "Spearman",
            uniqueUnitNote: "Gains a defensive bonus when adjacent to at least one other friendly melee unit.",
            cityNames: ["Athens", "Sparta", "Corinth", "Thebes", "Argos", "Megara", "Delphi", "Olympia", "Mycenae", "Ephesus", "Miletus"],
            blurb: "A constellation of fiercely independent city-states, Greece gave the world the assembly, the gymnasium, and the stubborn idea that citizens should rule themselves."
        ),
        Civilization(
            id: "egypt",
            name: "Egypt",
            adjective: "Egyptian",
            leader: "Hatshepsut",
            colorHex: "D4AF37",
            abilityName: "Gift of the Nile",
            abilityDescription: "Cities founded adjacent to a river produce wonders 20% faster and never suffer food shortages from drought.",
            uniqueUnitName: "Khopesh Guard",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Ignores movement penalties when crossing desert and floodplain tiles.",
            cityNames: ["Memphis", "Thebes", "Alexandria", "Heliopolis", "Giza", "Elephantine", "Abydos", "Edfu", "Tanis", "Bubastis", "Karnak"],
            blurb: "Cradled by the Nile's predictable floods, Egypt raised pyramids that outlasted empires and crowned a woman, Hatshepsut, as a pharaoh of trade and stone."
        ),
        Civilization(
            id: "babylon",
            name: "Babylon",
            adjective: "Babylonian",
            leader: "Hammurabi",
            colorHex: "5B7553",
            abilityName: "Tablets of Law",
            abilityDescription: "Completing a building in the capital grants a burst of science equal to its production cost, divided by four.",
            uniqueUnitName: "Sky-Wall Archer",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Deals additional damage to units attacking a city it occupies.",
            cityNames: ["Babylon", "Ur", "Uruk", "Nippur", "Kish", "Lagash", "Eridu", "Sippar", "Borsippa", "Larsa"],
            blurb: "On the silt plains between two rivers, Babylon carved the first great codes of law into stone and read destinies in the wheeling of the stars."
        ),
        Civilization(
            id: "persia",
            name: "Persia",
            adjective: "Persian",
            leader: "Cyrus the Great",
            colorHex: "7B2D8E",
            abilityName: "Royal Road",
            abilityDescription: "Trade routes between your own cities yield +2 gold and cannot be plundered while you are at peace.",
            uniqueUnitName: "Immortal",
            uniqueUnitReplaces: "Spearman",
            uniqueUnitNote: "Heals fully whenever it ends a turn inside friendly territory.",
            cityNames: ["Persepolis", "Pasargadae", "Susa", "Ecbatana", "Bactra", "Sardis", "Gordium", "Arbela", "Rhagae", "Anshan"],
            blurb: "Stretching from the Aegean to the Indus, Persia ruled by tolerance and tribute, knitting dozens of peoples together with royal roads and a king of kings."
        ),
        Civilization(
            id: "maya",
            name: "Maya",
            adjective: "Mayan",
            leader: "Lady Six Sky",
            colorHex: "1F7A5C",
            abilityName: "Long Count",
            abilityDescription: "Every time a new era begins, all your cities receive a one-time boost of culture and faith.",
            uniqueUnitName: "Atlatl Skirmisher",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Can move after attacking if it has movement remaining.",
            cityNames: ["Tikal", "Calakmul", "Palenque", "Copan", "Caracol", "Naranjo", "Yaxchilan", "Dos Pilas", "Quirigua", "Bonampak"],
            blurb: "Beneath the rainforest canopy, the Maya tracked the heavens with terrifying precision and built limestone cities whose glyphs still whisper royal histories."
        ),
        Civilization(
            id: "aztec",
            name: "Aztec",
            adjective: "Aztec",
            leader: "Moctezuma I",
            colorHex: "C75B12",
            abilityName: "Tribute of the Valley",
            abilityDescription: "Capturing or razing an enemy city refunds a portion of the attacking units' upkeep as gold for several turns.",
            uniqueUnitName: "Eagle Warrior",
            uniqueUnitReplaces: "Warrior",
            uniqueUnitNote: "Has a chance to capture a defeated enemy unit instead of destroying it.",
            cityNames: ["Tenochtitlan", "Texcoco", "Tlatelolco", "Tlacopan", "Azcapotzalco", "Xochimilco", "Culhuacan", "Tepexpan", "Cholula", "Tula"],
            blurb: "From an island city laced with canals and floating gardens, the Aztec forged a tribute empire that ruled the Valley of Mexico through war and ceremony."
        ),
        Civilization(
            id: "inca",
            name: "Inca",
            adjective: "Incan",
            leader: "Pachacuti",
            colorHex: "B59410",
            abilityName: "Terraces of the Sun",
            abilityDescription: "Cities work mountain-adjacent tiles for bonus food and production, and can build farms on hills at no extra cost.",
            uniqueUnitName: "Sling Runner",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Suffers no combat penalty fighting on hills or in mountain passes.",
            cityNames: ["Cusco", "Machu Picchu", "Ollantaytambo", "Pisac", "Vilcabamba", "Sacsayhuaman", "Tambo Colorado", "Cajamarca", "Tomebamba", "Quito"],
            blurb: "High in the Andes, the Inca terraced the mountainsides and stitched their realm together with stone roads and knotted cords no enemy could read."
        ),
        Civilization(
            id: "china",
            name: "China",
            adjective: "Chinese",
            leader: "Wu Zetian",
            colorHex: "E03A3A",
            abilityName: "Hundred Schools",
            abilityDescription: "Constructing a wonder grants a free technology toward the cheapest researchable advance.",
            uniqueUnitName: "Crossbow Levy",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Fires twice per turn while defending a city.",
            cityNames: ["Chang'an", "Luoyang", "Kaifeng", "Hangzhou", "Nanjing", "Chengdu", "Guangzhou", "Suzhou", "Xianyang", "Linzi", "Handan"],
            blurb: "Unified beneath the Mandate of Heaven, China invented paper, gunpowder, and the civil examination, and ruled an empire from behind its long northern wall."
        ),
        Civilization(
            id: "japan",
            name: "Japan",
            adjective: "Japanese",
            leader: "Hojo Tokimune",
            colorHex: "BC4A6B",
            abilityName: "Way of the Tide",
            abilityDescription: "Your units fight at full strength even when damaged, and coastal cities gain extra defense against naval attacks.",
            uniqueUnitName: "Samurai",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Does not lose combat strength as it takes damage.",
            cityNames: ["Kyoto", "Nara", "Osaka", "Kamakura", "Edo", "Sakai", "Hakata", "Hiraizumi", "Kanazawa", "Sendai", "Nagasaki"],
            blurb: "An archipelago shaped by sword and shrine, Japan married the discipline of the samurai to the refinement of the imperial court and the resilience of island defense."
        ),
        Civilization(
            id: "korea",
            name: "Korea",
            adjective: "Korean",
            leader: "Sejong the Great",
            colorHex: "3A86C7",
            abilityName: "Hall of Worthies",
            abilityDescription: "Cities with a science building generate bonus science equal to a quarter of their culture output.",
            uniqueUnitName: "Hwacha Crew",
            uniqueUnitReplaces: "Catapult",
            uniqueUnitNote: "Strikes all enemy units adjacent to its target for reduced damage.",
            cityNames: ["Seoul", "Gyeongju", "Pyongyang", "Kaesong", "Hanseong", "Buyeo", "Gongju", "Jinju", "Daegu", "Wonju"],
            blurb: "Between mountain and sea, Korea gave its people an alphabet of pure reason, rain gauges, and iron-clad ships that turned back invading fleets."
        ),
        Civilization(
            id: "mongolia",
            name: "Mongolia",
            adjective: "Mongolian",
            leader: "Genghis Khan",
            colorHex: "8A5A2B",
            abilityName: "Sea of Grass",
            abilityDescription: "Mounted units gain extra movement and heal each turn they remain on open or grassland tiles.",
            uniqueUnitName: "Steppe Rider",
            uniqueUnitReplaces: "Horseman",
            uniqueUnitNote: "Can fire a ranged shot before charging into melee.",
            cityNames: ["Karakorum", "Avarga", "Ondor", "Tsetserleg", "Khovd", "Bulgan", "Erdene", "Dalandzadgad", "Sarai", "Beshbalik"],
            blurb: "Out of the limitless steppe rode the Mongols, whose horse-archers stitched the largest contiguous empire in history together with terror and tolerance alike."
        ),
        Civilization(
            id: "india",
            name: "India",
            adjective: "Indian",
            leader: "Ashoka",
            colorHex: "F47B20",
            abilityName: "Edicts of Peace",
            abilityDescription: "Cities not at war grow faster, and large cities project happiness to your nearby smaller settlements.",
            uniqueUnitName: "War Elephant",
            uniqueUnitReplaces: "Knight",
            uniqueUnitNote: "Reduces the combat strength of all enemy units adjacent to it.",
            cityNames: ["Pataliputra", "Varanasi", "Ujjain", "Taxila", "Mathura", "Kannauj", "Vidisha", "Sravasti", "Rajagriha", "Kausambi", "Dwaraka"],
            blurb: "Along the great rivers of the subcontinent, India united warring kingdoms under one banner, then renounced conquest for compassion carved into pillars of stone."
        ),
        Civilization(
            id: "khmer",
            name: "Khmer",
            adjective: "Khmer",
            leader: "Jayavarman VII",
            colorHex: "6B8E23",
            abilityName: "Reservoir Kings",
            abilityDescription: "Building near fresh water lets a city store surplus food, releasing it as a growth surge when it would otherwise starve.",
            uniqueUnitName: "Temple Guard",
            uniqueUnitReplaces: "Spearman",
            uniqueUnitNote: "Earns faith for your civilization each time it defeats an enemy.",
            cityNames: ["Angkor", "Hariharalaya", "Yasodharapura", "Isanapura", "Koh Ker", "Sambor Prei Kuk", "Banteay Chhmar", "Lavo", "Vyadhapura", "Indrapura"],
            blurb: "In the monsoon forests of the Mekong, the Khmer engineered vast reservoirs and crowned them with the soaring towers of Angkor, the largest temple ever raised."
        ),
        Civilization(
            id: "songhai",
            name: "Songhai",
            adjective: "Songhai",
            leader: "Askia Muhammad",
            colorHex: "C9A227",
            abilityName: "River of Gold",
            abilityDescription: "Capturing a city or plundering a trade route yields double gold, and your river tiles produce extra commerce.",
            uniqueUnitName: "Niger Lancer",
            uniqueUnitReplaces: "Horseman",
            uniqueUnitNote: "Receives a strong attack bonus when assaulting a city.",
            cityNames: ["Gao", "Timbuktu", "Djenne", "Kukiya", "Walata", "Agadez", "Tadmekka", "Takedda", "Kano", "Katsina"],
            blurb: "Astride the great bend of the Niger, Songhai grew rich on salt and gold and turned Timbuktu into a city of scholars whose libraries drew seekers across the Sahara."
        ),
        Civilization(
            id: "mali",
            name: "Mali",
            adjective: "Malian",
            leader: "Mansa Musa",
            colorHex: "E0B84C",
            abilityName: "Pilgrim's Wealth",
            abilityDescription: "Religious buildings also generate gold, and your treasury earns interest each turn while you are at peace.",
            uniqueUnitName: "Mandinka Bowman",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Costs less gold to maintain than the unit it replaces.",
            cityNames: ["Niani", "Timbuktu", "Djenne", "Walata", "Gao", "Kangaba", "Tadmekka", "Diakha", "Segou", "Bamako"],
            blurb: "Mali's mansas commanded the trans-Saharan trade in gold and salt, and Mansa Musa's hajj scattered so much wealth that the markets of Cairo trembled for years."
        ),
        Civilization(
            id: "ethiopia",
            name: "Ethiopia",
            adjective: "Ethiopian",
            leader: "Ezana of Axum",
            colorHex: "1E7D4F",
            abilityName: "Highland Faith",
            abilityDescription: "Cities founded on or beside hills gain bonus faith, and units defending in your home terrain fight harder.",
            uniqueUnitName: "Shotelai",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Strikes with a curved blade that ignores part of an enemy's defensive bonus.",
            cityNames: ["Axum", "Adulis", "Lalibela", "Gondar", "Yeha", "Matara", "Adwa", "Debre Damo", "Ankober", "Harar"],
            blurb: "From the high tableland of the Horn, Axum minted its own coins, raised towering stelae, and carved churches straight down into living rock."
        ),
        Civilization(
            id: "zulu",
            name: "Zulu",
            adjective: "Zulu",
            leader: "Shaka",
            colorHex: "4A2C1A",
            abilityName: "Horns of the Bull",
            abilityDescription: "When two of your melee units attack the same enemy in one turn, both deal increased damage.",
            uniqueUnitName: "Impi",
            uniqueUnitReplaces: "Spearman",
            uniqueUnitNote: "Moves an extra tile and may attack immediately after a forced march.",
            cityNames: ["Ulundi", "Nodwengu", "Bulawayo", "Gibixhegu", "Mgungundlovu", "eMakhosini", "Nobamba", "Dukuza", "kwaBulawayo", "Esiklebheni"],
            blurb: "On the rolling veld of southern Africa, the Zulu drilled their regiments into a single sweeping weapon, encircling foes like the horns of a charging bull."
        ),
        Civilization(
            id: "carthage",
            name: "Carthage",
            adjective: "Carthaginian",
            leader: "Hannibal Barca",
            colorHex: "2BAE9E",
            abilityName: "Masters of the Sea",
            abilityDescription: "Naval units cost less to build, and coastal cities can construct ships even without an adjacent harbor.",
            uniqueUnitName: "Quinquereme",
            uniqueUnitReplaces: "Trireme",
            uniqueUnitNote: "Carries an embarked land unit and shields it from attack while aboard.",
            cityNames: ["Carthage", "Utica", "Hadrumetum", "Hippo", "Lepcis", "Gadir", "Panormus", "Lilybaeum", "Tharros", "Mahdia"],
            blurb: "A merchant empire spread across the western sea, Carthage answered Rome with elephants over the Alps and trading fleets that ruled the Mediterranean's edges."
        ),
        Civilization(
            id: "macedon",
            name: "Macedon",
            adjective: "Macedonian",
            leader: "Alexander the Great",
            colorHex: "0E5AA7",
            abilityName: "To the Ends of the Earth",
            abilityDescription: "Capturing a city refreshes the movement of nearby units and reduces war weariness for several turns.",
            uniqueUnitName: "Companion Cavalry",
            uniqueUnitReplaces: "Horseman",
            uniqueUnitNote: "Gains experience twice as fast as the unit it replaces.",
            cityNames: ["Pella", "Aigai", "Thessalonica", "Amphipolis", "Pydna", "Dion", "Edessa", "Stagira", "Methone", "Beroea"],
            blurb: "From a rough northern kingdom, Macedon's phalanx and companions broke the Persian colossus and carried Greek cities to the banks of the distant Indus."
        ),
        Civilization(
            id: "scythia",
            name: "Scythia",
            adjective: "Scythian",
            leader: "Tomyris",
            colorHex: "9C6BC4",
            abilityName: "Riders of the Wind",
            abilityDescription: "Mounted and ranged units recover health each turn they defeat or wound an enemy.",
            uniqueUnitName: "Horse Archer",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Retains full movement after firing, allowing it to strike and withdraw.",
            cityNames: ["Gelonus", "Kamenka", "Belsk", "Neapolis", "Kul-Oba", "Pazyryk", "Arzhan", "Solokha", "Chertomlyk", "Tolstaya"],
            blurb: "Masters of the open grassland, the Scythians lived in the saddle, buried their queens with gold and horses, and humbled empires that dared chase them."
        ),
        Civilization(
            id: "gaul",
            name: "Gaul",
            adjective: "Gallic",
            leader: "Vercingetorix",
            colorHex: "3F7D44",
            abilityName: "Forest Clans",
            abilityDescription: "Units fighting inside forest or near unworked tiles gain a combat bonus, and mines yield extra culture.",
            uniqueUnitName: "Oathsworn",
            uniqueUnitReplaces: "Warrior",
            uniqueUnitNote: "Grows stronger for each adjacent friendly unit when it attacks.",
            cityNames: ["Bibracte", "Gergovia", "Alesia", "Lutetia", "Avaricum", "Cenabum", "Vienna", "Nemausus", "Burdigala", "Lugdunum"],
            blurb: "Among the oaks and hill-forts of ancient Gaul, fierce clans of warriors and druids united, briefly, to throw their full weight against the legions of Rome."
        ),
        Civilization(
            id: "norway",
            name: "Norway",
            adjective: "Norse",
            leader: "Harald Hardrada",
            colorHex: "1B5E8C",
            abilityName: "Sons of the Sea",
            abilityDescription: "Your ships may move into ocean tiles early and pillage coastal improvements without first declaring open war.",
            uniqueUnitName: "Longship",
            uniqueUnitReplaces: "Galley",
            uniqueUnitNote: "Heals while in coastal waters and can raid land tiles adjacent to the shore.",
            cityNames: ["Nidaros", "Bergen", "Tunsberg", "Oslo", "Hamar", "Skiringssal", "Borre", "Stavanger", "Kaupang", "Trondheim"],
            blurb: "From fjord-cut shores the Norse launched their dragon ships across cold seas, raiding, trading, and settling from Dublin to the rivers of the distant east."
        ),
        Civilization(
            id: "england",
            name: "England",
            adjective: "English",
            leader: "Elizabeth I",
            colorHex: "C0392B",
            abilityName: "Mistress of the Waves",
            abilityDescription: "Naval units gain extra sight and movement, and overseas cities suffer no extra distance penalties.",
            uniqueUnitName: "Longbowman",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Attacks from one additional tile of range compared to standard archers.",
            cityNames: ["London", "York", "Winchester", "Canterbury", "Norwich", "Bristol", "Exeter", "Lincoln", "Oxford", "Plymouth", "Dover"],
            blurb: "An island kingdom that learned to make the sea its frontier, England turned wool, longbows, and ocean-going galleons into the seeds of a global reach."
        ),
        Civilization(
            id: "france",
            name: "France",
            adjective: "French",
            leader: "Eleanor of Aquitaine",
            colorHex: "274C9E",
            abilityName: "Courts of Renown",
            abilityDescription: "Wonders generate extra culture and tourism, and your cities exert stronger cultural pressure on rivals.",
            uniqueUnitName: "Gendarme",
            uniqueUnitReplaces: "Knight",
            uniqueUnitNote: "Suffers no movement penalty charging into open or farmed terrain.",
            cityNames: ["Paris", "Orleans", "Reims", "Tours", "Lyon", "Marseille", "Rouen", "Bordeaux", "Avignon", "Poitiers", "Carcassonne"],
            blurb: "From cathedral towns and vineyard valleys, France made culture a weapon, its courts of love and learning radiating taste and influence across a continent."
        ),
        Civilization(
            id: "spain",
            name: "Spain",
            adjective: "Spanish",
            leader: "Isabella I",
            colorHex: "E0A800",
            abilityName: "New Horizons",
            abilityDescription: "Settling a city on a distant continent grants a one-time burst of gold and faith.",
            uniqueUnitName: "Conquistador",
            uniqueUnitReplaces: "Knight",
            uniqueUnitNote: "Can found a city itself and fights at full strength far from home territory.",
            cityNames: ["Toledo", "Sevilla", "Cordoba", "Granada", "Valencia", "Zaragoza", "Burgos", "Salamanca", "Cadiz", "Segovia", "Madrid"],
            blurb: "Forged in centuries of reconquest, Spain looked west across the ocean and planted its banners and faith on shores no European map had yet drawn."
        ),
        Civilization(
            id: "russia",
            name: "Russia",
            adjective: "Russian",
            leader: "Catherine the Great",
            colorHex: "6E4B9E",
            abilityName: "Vast Frontier",
            abilityDescription: "Newly founded cities claim extra surrounding territory, and tundra tiles yield additional production.",
            uniqueUnitName: "Cossack",
            uniqueUnitReplaces: "Horseman",
            uniqueUnitNote: "Fights harder against any enemy unit that has already taken damage.",
            cityNames: ["Moscow", "Novgorod", "Kiev", "Vladimir", "Suzdal", "Pskov", "Smolensk", "Tver", "Ryazan", "Yaroslavl", "Rostov"],
            blurb: "Spread across forest, steppe, and endless winter, Russia turned sheer distance into a shield and patiently gathered scattered principalities into an empire."
        ),
        Civilization(
            id: "ottomans",
            name: "Ottomans",
            adjective: "Ottoman",
            leader: "Suleiman the Magnificent",
            colorHex: "0B6E4F",
            abilityName: "Gunpowder Sultanate",
            abilityDescription: "Captured cities recover and grow more quickly, and siege units cost less to produce.",
            uniqueUnitName: "Janissary",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Heals partially each time it defeats an enemy unit.",
            cityNames: ["Constantinople", "Bursa", "Edirne", "Konya", "Izmir", "Ankara", "Trabzon", "Antalya", "Manisa", "Diyarbakir"],
            blurb: "Straddling two continents from the walls of Constantinople, the Ottomans fused cannon and law into an empire that endured for six unbroken centuries."
        ),
        Civilization(
            id: "arabia",
            name: "Arabia",
            adjective: "Arabian",
            leader: "Harun al-Rashid",
            colorHex: "138D75",
            abilityName: "House of Wisdom",
            abilityDescription: "Each holy site or library you build also produces a small amount of science for every neighboring city.",
            uniqueUnitName: "Desert Lancer",
            uniqueUnitReplaces: "Horseman",
            uniqueUnitNote: "Crosses desert tiles without movement penalty and ambushes from them with a bonus.",
            cityNames: ["Mecca", "Medina", "Baghdad", "Damascus", "Basra", "Kufa", "Najran", "Sana'a", "Taif", "Yathrib"],
            blurb: "From the oasis cities of the desert poured a faith and a flowering of learning that preserved the ancient world and gave it algebra, astronomy, and the zero."
        ),
        Civilization(
            id: "polynesia",
            name: "Polynesia",
            adjective: "Polynesian",
            leader: "Hotu Matua",
            colorHex: "1CA6B0",
            abilityName: "Wayfinders",
            abilityDescription: "Your ships and embarked units may cross open ocean from the start of the game and sight distant coasts farther away.",
            uniqueUnitName: "Outrigger Raider",
            uniqueUnitReplaces: "Galley",
            uniqueUnitNote: "Moves an extra tile across open water and embarks land units faster.",
            cityNames: ["Hanga Roa", "Papeete", "Nuku Hiva", "Avarua", "Apia", "Hilo", "Honolulu", "Rarotonga", "Taputapuatea", "Vailima"],
            blurb: "Reading swell, star, and bird, Polynesian navigators settled a third of the globe's surface, finding pinpricks of land scattered across the open Pacific."
        ),
        Civilization(
            id: "america",
            name: "America",
            adjective: "American",
            leader: "Abraham Lincoln",
            colorHex: "3C5488",
            abilityName: "Manifest Industry",
            abilityDescription: "Cities founded on or beside new continents work tiles at greater range and gain extra production from factories.",
            uniqueUnitName: "Frontier Rifles",
            uniqueUnitReplaces: "Archer",
            uniqueUnitNote: "Gains a defensive bonus when entrenched outside of friendly cities.",
            cityNames: ["Philadelphia", "Boston", "New York", "Charleston", "Baltimore", "Savannah", "Richmond", "Albany", "Annapolis", "Providence", "Hartford"],
            blurb: "Born of revolution and stitched from many peoples, America pushed across a continent on rail and rifle, wagering everything on a fragile experiment in self-rule."
        ),
        Civilization(
            id: "germany",
            name: "Germany",
            adjective: "German",
            leader: "Otto von Bismarck",
            colorHex: "2C3E50",
            abilityName: "Free Imperial Cities",
            abilityDescription: "Each city may support one extra building beyond its normal limit, and workshops produce additional output.",
            uniqueUnitName: "Landsknecht",
            uniqueUnitReplaces: "Swordsman",
            uniqueUnitNote: "Costs little to maintain and fights well against mounted enemies.",
            cityNames: ["Aachen", "Cologne", "Frankfurt", "Nuremberg", "Mainz", "Trier", "Hamburg", "Lubeck", "Augsburg", "Magdeburg", "Worms"],
            blurb: "A patchwork of free cities, princes, and guilds, the German lands turned craft and coal into industry and, late but decisively, into a single iron-bound nation."
        ),
        Civilization(
            id: "netherlands",
            name: "Netherlands",
            adjective: "Dutch",
            leader: "William the Silent",
            colorHex: "E67E22",
            abilityName: "Polder and Profit",
            abilityDescription: "Cities can reclaim and farm coastal water tiles for food, and trade routes overseas yield extra gold.",
            uniqueUnitName: "Sea Beggar",
            uniqueUnitReplaces: "Galley",
            uniqueUnitNote: "Earns gold for your treasury whenever it sinks an enemy ship.",
            cityNames: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Leiden", "Delft", "Haarlem", "Groningen", "Maastricht", "Nijmegen", "Dordrecht"],
            blurb: "Wresting their land from the sea behind dikes and windmills, the Dutch built a republic of merchants whose ships and ledgers reached every ocean of the world."
        ),
    ]

    static func by(id: String) -> Civilization? { all.first { $0.id == id } }
    static var random: Civilization { all.randomElement()! }
}
